# Exported from Render on 2024-12-05T19:36:20Z
services:
- type: web
  name: pinecone-ucb
  runtime: node
  repo: https://github.com/EddyEscalanteU/pinecone
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: PINECONE_INDEX_NAME
    sync: false
  - key: PINECONE_ENVIRONMENT
    sync: false
  - key: PINECONE_API_KEY
    sync: false
  region: virginia
  buildCommand: npm install && npm run build
  startCommand: node dist/index.js
version: "1"
